#!/usr/bin/env ruby

filename = ARGV[0]
raise "You need to pass in a filename to run!" if filename.nil?

folder = ARGV[0].split("/").first

if File.file?("#{folder}/example2.txt") 
    system("cat #{folder}/example2.txt | #{filename}")
else
    system("cat #{folder}/example.txt | #{filename}")
end

